### PR TITLE
ci: add

### PR DESCRIPTION
**Pull request by LeoDog896**
This adds a lint check with `awesome-lint` into the CI pipeline. With it, it also removes some violators of the linter

- fixes the ToC
- removes `...` from the Draconic Evolution description
- Unnecessary License portion
- NodeJS -> Node.js

### CODE REVIEW

**Comment by g-plane** [comment]
Thanks, but I think Awesome Lint is too opinionated.

**Comment by LeoDog896** [comment]
Thanks for the feedback! I'm actually aiming to obtain some more opinions about awesome-lint and the community - I've noticed similar problems with awesome-modrinth as well. What do you currently have against awesome-lint atm?

**Comment by g-plane** [comment]
I think Markdown lint is good enough, while most of rules from Awesome Lint are specialized for https://github.com/sindresorhus/awesome, but we don't need those rules.

**Comment by LeoDog896** [comment]
Alright, thanks for your words!

**Pull request closed without merging**
